edbe/Areas/Y/Controllers/PContentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using edbe.Models;

namespace edbe.Areas.Y.Controllers
{
    [Authorize]
    public class PContentController : BController
    {
        public ActionResult Index()
        {

            //app.min.js       ----- hasClass("expand")?($(this).removeClass("expand").addClass("collapse")
            // tabloların kapanıp açılmasını terse çevirdim !



            var contentCategories = Entity.ContentCategory.ToList().OrderBy(F=>F.IndexNo);
            return View(contentCategories);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            try
            {
                ViewBag.ContentCategories = Entity.ContentCategory.ToList();
                Content content = Entity.Content.FirstOrDefault(F => F.ContentCategoryID == id);
                if (content == null)
                {
                    return HttpNotFound();
                }
                return View(content);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            try
            {
                ViewBag.ContentCategoryID = Entity.ContentCategory.First(F=>F.SubCategoryID == id).Id;
                return View();
            }
            catch
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ContentCategoryID,Name,Title,Html")] Content content)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Entity.Content.First(F => F.ContentCategoryID == content.ContentCategoryID);
                    return RedirectToAction("Index");
                }
                catch
                {
                    Entity.Content.Add(content);
                    Entity.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.ContentCategoryID = new SelectList(Entity.ContentCategory, "Id", "Name", content.ContentCategoryID);
            return View(content);
        }

        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Content content = Entity.Content.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            ViewBag.ContentCategoryID = content.ContentCategoryID;
           
            return View(content);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id,ContentCategoryID,Name,Title,Html")] Content content)
        {
            if (ModelState.IsValid)
            {
                Entity.Entry(content).State = EntityState.Modified;
                ContentCategory category  =  Entity.ContentCategory.Find(content.ContentCategoryID);
                category.Name = content.Name;
                Entity.SaveChanges();
                int id = content.ContentCategoryID.Value;
                return RedirectToAction("Details/"+id);
            }
            ViewBag.ContentCategoryID = content.ContentCategoryID;
            return View(content);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Entity.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

edbe/Areas/Y/Views/PContent/Details.cshtml
@model edbe.Models.Content

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Y/Views/Shared/_LayoutPage1.cshtml";

    List<edbe.Models.ContentCategory> Category = (List<edbe.Models.ContentCategory>)ViewBag.ContentCategories;
    List<edbe.Models.ContentCategory> CategoryBase = Category.Where(f => f.SubCategoryID == 0).OrderBy(f => f.IndexNo).ToList();
    List<edbe.Models.ContentCategory> categories = Category.Where(f => f.SubCategoryID != 0).ToList();

    //var CategoryBase = Model.Where(F => F.SubCategoryID == 0).ToList();
    //var categories = Model.Where(f => f.SubCategoryID != 0).OrderBy(f => f.SubCategoryID).ToList();
}

<h3>Kategori Bilgileri</h3>

<div class="row">
    <div class="col-md-8">
        <div>
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject font-blue-sharp bold uppercase">@Html.DisplayFor(model => model.Name)</span>
                    </div>

                    <div class="actions">
                      
                        <a class="btn btn-circle btn-icon-only btn-default" href="@Url.Action("Edit","PContent",new { id = Model.Id})">
                            <i class="fa fa-edit"></i>
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                   <h1 class="text-center">@Html.DisplayFor(model => model.Title)</h1> 
                      <div class="row">
                        <div class="col-md-12">
                           @Html.Raw(Model.Html)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    </div>

    @{
        foreach (var v in CategoryBase)
        {
            <div class="col-md-4">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>@v.Name
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse" data-original-title="Gizle/Göster" title="Gizle/Göster"> </a>
                            <a href="javascript:;" class="remove" data-original-title="Kaldır" title="Kaldır"> </a>
                        </div>
                    </div>
                    <div class="portlet-body" style="display:none">
                        <div class="table-scrollable">
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th> Kategori Adı</th>
                                        <th> Sıra No</th>
                                        <th> </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in categories.Where(f => f.SubCategoryID == v.Id).OrderBy(F => F.IndexNo))
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.IndexNo)
                                            </td>
                                            <td>
                                                @Html.ActionLink("İçeriği Gör", "details", new { id = item.Id }, new { @class = "btn blue btn-sm " })
                                            </td>
                                        </tr>
                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        }
    }



</div>

edbe/Areas/Y/Views/PContent/Edit.cshtml
@model edbe.Models.Content

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Y/Views/Shared/_LayoutPage1.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>İçerik Düzenleme Bölümü</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <input type="hidden" name="ContentCategoryID" value="@ViewBag.ContentCategoryID"/>
        
        <div class="form-group">
            @Html.Label("Kategori Adı :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Sayfa Başlığı :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("İçerik Bölümü :", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Html)
                @Html.ValidationMessageFor(model => model.Html, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn blue" />
                @Html.ActionLink("Geri Dön", "Index","",new { @class="btn default"})
            </div>
        </div>
    </div>
}


<script src="~/Areas/Y/Content/ckfinder/ckfinder.js"></script>
<script src="~/Areas/Y/Content/ckeditor/ckeditor.js"></script>
<script src="~/scripts/jquery-1.10.2.js"></script>
<script src="~/scripts/jquery.validate.min.js"></script>
<script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Areas/Y/Content/ckfinder/ckfinder.js"></script>

<script type="text/javascript">
    var editor = CKEDITOR.instances['Html'];
            if (editor) { editor.destroy(true); }
            CKEDITOR.replace('Html', {
            enterMode: CKEDITOR.ENTER_BR,
            });
            CKFinder.setupCKEditor(null, '@Url.Content("~/Content/images/UploadedPhoto/")');
</script>

edbe/Areas/Y/Views/PContent/Index.cshtml
@model IEnumerable<edbe.Models.ContentCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Y/Views/Shared/_LayoutPage1.cshtml";

    var CategoryBase = Model.Where(F => F.SubCategoryID == 0).ToList();
    var categories = Model.Where(f => f.SubCategoryID != 0).OrderBy(f => f.SubCategoryID).ToList();

}


<h3 class="page-title">
    İçerik
</h3>
<div class="row">

    <div class="col-md-8">
        <div>
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject font-red-sharp bold uppercase" style="color:red">ÖRNEK KATEGORİ</span>
                    </div>

                    <div class="actions">

                        <a class="btn btn-circle btn-icon-only btn-default" href="#">
                            <i class="fa fa-edit"></i>
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <h1 class="text-center" style="color:red">Sayfa Başlığı</h1>
                    <div class="row">
                        <div class="col-md-12">
                            <p style="color:red"> Paragraf Bilgileri </p>
                            <p style="color:red"> Girmek istediğiniz bilgiler görmüş olduğunuz tasarımdaki gibi kaydedilecektir.</p>
                            <p style="color:red"> Bir kategoriyi düzenlemek isterseniz sağ üstteki icon'a tıklamanız yeterli olacaktır.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @{
        foreach (var v in CategoryBase)
        {
            <div class="col-md-4">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>@v.Name
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse" data-original-title="Gizle/Göster" title="Gizle/Göster"> </a>
                            <a href="javascript:;" class="remove" data-original-title="Kaldır" title="Kaldır"> </a>
                        </div>
                    </div>
                    <div class="portlet-body" style="display:none">
                        <div class="table-scrollable">
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th> Kategori Adı</th>
                                        <th> Sıra No</th>
                                        <th> </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in categories.Where(f => f.SubCategoryID == v.Id).OrderBy(F=>F.IndexNo))
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.IndexNo)
                                            </td>
                                            <td>
                                                @Html.ActionLink("İçeriği Gör", "details", new { id = item.Id }, new { @class = "btn blue btn-sm " })
                                            </td>
                                        </tr>
                                    }
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        }
    }

</div>